services:
  db:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - task_manager_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_manager"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: task_manager_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AI_SERVICE_URL: http://ai:5000
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  ai:
    build: ./src/main/ai_service
    container_name: task_manager_ai
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: task_manager
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  task_manager_pg:
