spring.datasource.url=jdbc:postgresql://db:5432/task_manager?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=password

server.port=8081

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

spring.flyway.clean-disabled=false
